sudo: false
dist: trusty
language: java

# https://github.com/sormuras/sormuras.github.io/blob/master/.travis.yml
before_install:
- unset -v _JAVA_OPTIONS
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:

  - env:
    - JDK=1.8
    - DIST=OpenJDK
    install: jdk_switcher use openjdk8
  - env:
    - JDK=9
    - DIST=OpenJDK
    install: source install-jdk.sh -F 9
  - env:
    - JDK=10
    - DIST=OpenJDK
    install: source install-jdk.sh -F 10
  - env:
    - JDK=11
    - DIST=OpenJDK
    install: source install-jdk.sh -F 11
  - env:
    - JDK=12
    - DIST=OpenJDK
    install: source install-jdk.sh -F 12

  - env:
    - JDK=1.8
    - DIST=OracleJDK
    install: jdk_switcher use oraclejdk8
  - env:
    - JDK=9
    - DIST=OracleJDK
    install: jdk_switcher use oraclejdk9
  - env:
    - JDK=10
    - DIST=OracleJDK
    install: source install-jdk.sh -F 10 -L BCL
  - env:
    - JDK=11
    - DIST=OracleJDK
    install: source install-jdk.sh -F 11 -L BCL

script:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}
- ls ${JAVA_HOME}
- java -version
- mvn clean compile -Djava.version=$JDK
