sudo: false
dist: trusty
language: java

# https://github.com/sormuras/sormuras.github.io/blob/master/.travis.yml
before_install:
- unset -v _JAVA_OPTIONS
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:

  - stage: OpenJDK
    env: JDK=1.8
    install: jdk_switcher use openjdk8
  - # stage: ...
    env: JDK=9
    install: source install-jdk.sh -F 9
  - # stage: ...
    env: JDK=10
    install: source install-jdk.sh -F 10
  - # stage: ...
    env: JDK=11
    install: source install-jdk.sh -F 11
  - # stage: ...
    env: JDK=12
    install: source install-jdk.sh -F 12

  - stage: Oracle JDK
    env: JDK=1.8
    install: jdk_switcher use oraclejdk8
  - # stage: ...
    env: JDK=9
    install: source install-jdk.sh -F 9 -L BCL
  - # stage: ...
    env: JDK=10
    install: source install-jdk.sh -F 10 -L BCL
  - # stage: ...
    env: JDK=11
    install: source install-jdk.sh -F 11 -L BCL

script:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}
- ls ${JAVA_HOME}
- java -version
- mvn clean compile -Djava.version=$JDK
